import {
  ETH_NETWORK,
  ETH_RPC,
  GSN_PAYMASTER_CONTRACT_ADDRESS,
  GSN_SC_RELAY,
  SC_FARCASTER_LEDGER_CONTRACT_ADDRESS,
  SC_FARCASTER_POSTS_CONTRACT_ADDRESS,
  TWITTER_URL,
  VERIFY_URL,
} from '@big-whale-labs/constants'
import { cleanEnv, str } from 'envalid'

export default cleanEnv(import.meta.env, {
  VITE_ENCRYPT_KEY: str(),
  VITE_APP_NAME: str(),
  VITE_ETH_NETWORK: str({ default: ETH_NETWORK }),
  VITE_ETH_RPC: str({ default: ETH_RPC }),
  VITE_SC_FARCASTER_LEDGER_CONTRACT_ADDRESS: str({
    default: SC_FARCASTER_LEDGER_CONTRACT_ADDRESS,
  }),
  VITE_SC_FARCASTER_POSTS_CONTRACT_ADDRESS: str({
    default: SC_FARCASTER_POSTS_CONTRACT_ADDRESS,
  }),
  VITE_GSN_PAYMASTER_CONTRACT_ADDRESS: str({
    default: GSN_PAYMASTER_CONTRACT_ADDRESS,
  }),
  VITE_GSN_SC_RELAY: str({ default: GSN_SC_RELAY }),
  VITE_VERIFY_URL: str({ default: VERIFY_URL }),
  VITE_FARCASTER_PROFILE_URL: str(),
  VITE_TWITTER_POSTER_URL: str({ default: TWITTER_URL }),
})
