name: Build and deploy app
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-app:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install modules
        run: yarn
        shell: bash
      - name: Build code
        env:
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
          VITE_ENCRYPT_KEY: ${{ secrets.VITE_ENCRYPT_KEY }}
        run: yarn build
        shell: bash
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - uses: sarisia/actions-status-discord@v1
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          nodetail: true
          title: 'Success'
          description: |
            ✅ [sealcaster.xyz](https://sealcaster.xyz) deployed
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          nodetail: true
          title: 'Failed'
          description: |
            💥 [sealcaster.xyz](https://sealcaster.xyz) failed to deploy @dev
